### ISSUE TITLE
Verify permission checks

### ISSUE THREAD

**Issue by neteler** [actinia-org/actinia-statistic-plugin#9]
> `EphemeralProcessing._execute(self, skip_permission_check=True)`

It is save to skip the permission check because this is handled elsewhere, correct? We are calling it internally and therefore no check needed, right?

_Originally posted by @marcjansen in https://github.com/mundialis/actinia_statistic_plugin/pull/8#r829230091_

**Comment by anikaweinmann** [comment]
`skip_permission_check=True` is tested with the following results:

- if the user does **not** have access to **mapset/location**, then the process **fails**, despite the skip
- the **module** check is **ignored**
   - https://github.com/mundialis/actinia_core/blob/main/src/actinia_core/processing/actinia_processing/ephemeral_processing.py#L1420-L1422
   - https://github.com/mundialis/actinia_core/blob/main/src/actinia_core/processing/actinia_processing/ephemeral_processing.py#L579-L589
  
- **process_num_limit** is **ignored**
  - https://github.com/mundialis/actinia_core/blob/main/src/actinia_core/processing/actinia_processing/ephemeral_processing.py#L1420-L1422
   - https://github.com/mundialis/actinia_core/blob/main/src/actinia_core/processing/actinia_processing/ephemeral_processing.py#L566-L570
 - **CELL_LIMIT** is **not ignored**
 - **PROCESS_TIME_LIMIT** is **ignored**

**Comment by anikaweinmann** [comment]
**TODO:** Documentate in https://github.com/mundialis/actinia-example-plugin
